# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2bd4a205c93b3ce80d331d8626cc47952746d0948a8cbc32758d9ee1b652e0870e7bf1d4176a8f1974f27a1f69a257e6f412ba96ab95c5100b30c91e976123ff

test:
  secret_key_base: 6adca4067665f6a7dc88ae5c8d8e222ce69edc9152bd5d006a409960f8abbf4ba4486056cf1d01deeaf07674e8ba62ddb98711168c557e8d9900291f168a64bb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
